from langchain_core.tools import tool
from app.database.DbConnection import db
from bson import ObjectId
from app.utils.dates import parse_date, get_period_dates

def product_analysis(organization_id):

    @tool
    def analyze_products(
        period: str = None,
        analysis: str = None,
        product_id: str = None,
        category: str = None,
        limit: int = None
    ):
        """
        Analyze product sales performance and product revenue.

        USE THIS TOOL when the user asks which products sell the most,
        which products generate the most revenue, product sales,
        product revenue, or sales performance by category.

        Do NOT use this tool for current inventory or stock availability.
        Use analyze_inventory for stock-related questions.

        Do NOT use this tool for general business revenue without a
        product-related question. Use analyze_sales for overall revenue.

        analysis determines the product analysis:

        - top_selling:
            Rank products by number of units sold.
            Use for:
            "What is my best-selling product?"
            "Which products sold the most?"
            "Show me my top 5 products by sales."

        - highest_revenue:
            Rank products by revenue generated from completed sales.
            Use for:
            "Which product made the most money?"
            "What product generates the most revenue?"

        - sales_by_category:
            Summarize product sales by category.
            Use for:
            "Which category sells the most?"
            "How many units did each category sell?"

        - product_revenue:
            Calculate revenue generated by a specific product or
            return product revenue results.
            Use for:
            "How much revenue did the Wireless Mouse generate?"

        - product_sales:
            Calculate units sold for a specific product or return
            product sales results.
            Use for:
            "How many Wireless Mouse units have I sold?"

        - category_sales:
            Analyze sales performance for a specific category.
            Use for:
            "How much did the electronics category sell?"
            "How many products did I sell in the accessories category?"

        period specifies the sales period:
        - today
        - this_week
        - this_month
        - last_month
        - this_year
        - last_year
        - all_time
        - None = all available data

        product_id:
            Use when the user asks about one specific product whose
            ID is already known.

        category:
            Use when the user specifies a product category.

        limit:
            Use for rankings such as top-selling or highest-revenue products.
            Keep the value small unless the user explicitly requests more.

        IMPORTANT:
        Product sales and revenue should normally be calculated from
        completed orders unless the user explicitly asks for another
        order status.
        """

        if limit is None:
            limit = 5

        start, end = get_period_dates(period)

        query = {
            "organization": organization_id,
            "status": "completed"
        }

        if start:
            query["completedAt"] = {
                "$gte": start,
                "$lt": end
            }

        if product_id:
            try:
                product_oid = ObjectId(product_id)
            except Exception:
                return {"error": "Invalid product ID"}

            query["products.product"] = product_oid

        pipeline = [
            {"$match": query},
            {"$unwind": "$products"}
        ]

        if product_id:
            pipeline.append({
                "$match": {
                    "products.product": product_oid
                }
            })

        # Sales by category
        if analysis in [
            "sales_by_category",
            "category_sales"
        ]:

            pipeline.extend([
                {
                    "$lookup": {
                        "from": "products",
                        "localField": "products.product",
                        "foreignField": "_id",
                        "as": "product"
                    }
                },
                {"$unwind": "$product"}
            ])

            if category:
                pipeline.append({
                    "$match": {
                        "product.category": category
                    }
                })

            pipeline.extend([
                {
                    "$group": {
                        "_id": "$product.category",
                        "unitsSold": {
                            "$sum": "$products.quantity"
                        },
                        "revenue": {
                            "$sum": {
                                "$multiply": [
                                    "$products.quantity",
                                    "$products.priceAtPurchase"
                                ]
                            }
                        }
                    }
                },
                {"$sort": {"revenue": -1}},
                {
                    "$project": {
                        "_id": 0,
                        "category": "$_id",
                        "unitsSold": 1,
                        "revenue": 1
                    }
                }
            ])

            return list(db.orders.aggregate(pipeline))

        # Product ranking
        pipeline.extend([
            {
                "$group": {
                    "_id": "$products.product",
                    "unitsSold": {
                        "$sum": "$products.quantity"
                    },
                    "revenue": {
                        "$sum": {
                            "$multiply": [
                                "$products.quantity",
                                "$products.priceAtPurchase"
                            ]
                        }
                    }
                }
            }
        ])

        if analysis == "highest_revenue":
            pipeline.append({
                "$sort": {
                    "revenue": -1
                }
            })
        else:
            pipeline.append({
                "$sort": {
                    "unitsSold": -1,
                    "revenue": -1
                }
            })

        pipeline.extend([
            {"$limit": limit},
            {
                "$lookup": {
                    "from": "products",
                    "localField": "_id",
                    "foreignField": "_id",
                    "as": "product"
                }
            },
            {"$unwind": "$product"},
            {
                "$project": {
                    "_id": 0,
                    "productId": "$product._id",
                    "name": "$product.name",
                    "category": "$product.category",
                    "unitsSold": 1,
                    "revenue": 1
                }
            }
        ])

        return list(db.orders.aggregate(pipeline))

    return [analyze_products]