from langchain_core.tools import tool
from app.database.DbConnection import db
from bson import ObjectId
from app.utils.dates import parse_date, get_period_dates
import json

def product_analysis(organization_id):

    @tool
    def analyze_products(
        period: str | None = None,
        analysis: str | None = None,
        product_id: str | None = None,
        category: str | None = None,
        status: str | None = "completed",
        limit: int | None = None
    ):
        """
        Analyze product sales performance and revenue from orders.

        Use for queries about top-selling products, revenue stats, or category sales.
        Do NOT use for inventory/stock (use analyze_inventory) or overall business revenue without products (use analyze_sales).

        Parameters:
        - analysis: Type of analysis to perform.
            - top_selling: Rank products by units sold.
            - highest_revenue / product_revenue: Rank or calculate revenue generated by products.
            - sales_by_category / category_sales: Summarize sales by product category.
        - period: Timeframe (today, this_week, this_month, last_month, this_year, last_year, all_time).
        - product_id: Filter by a specific product ID.
        - category: Filter by a specific product category.
        - status: Order status filter (defaults to "completed", can be changed to "pending", etc.).
        - limit: Max number of results for rankings (defaults to 5).

        IMPORTANT:
        Product sales and revenue should normally be calculated from
        completed orders unless the user explicitly asks for another
        order status.
        """

        if limit is None:
            limit = 5

        start, end = get_period_dates(period)

        query = {
            "organization": organization_id,
            "status": status
        }

        if start:
            date_field = "completedAt" if status == "completed" else "createdAt"
            query[date_field] = {
            "$gte": start,
            "$lt": end
        }

        if product_id:
            try:
                product_oid = ObjectId(product_id)
            except Exception:
                return {"error": "Invalid product ID"}

            query["products.product"] = product_oid

        pipeline = [
            {"$match": query},
            {"$unwind": "$products"}
        ]

        if product_id:
            pipeline.append({
                "$match": {
                    "products.product": product_oid
                }
            })

        # Sales by category
        if analysis in [
            "sales_by_category",
            "category_sales"
        ]:

            pipeline.extend([
                {
                    "$lookup": {
                        "from": "products",
                        "localField": "products.product",
                        "foreignField": "_id",
                        "as": "product"
                    }
                },
                {"$unwind": "$product"}
            ])

            if category:
                pipeline.append({
                    "$match": {
                        "product.category": category
                    }
                })

            pipeline.extend([
                {
                    "$group": {
                        "_id": "$product.category",
                        "unitsSold": {
                            "$sum": "$products.quantity"
                        },
                        "revenue": {
                            "$sum": {
                                "$multiply": [
                                    "$products.quantity",
                                    "$products.priceAtPurchase"
                                ]
                            }
                        }
                    }
                },
                {"$sort": {"revenue": -1,"unitsSold": -1,"_id":1}},
                {
                    "$project": {
                        "_id": 0,
                        "category": "$_id",
                        "unitsSold": 1,
                        "revenue": 1
                    }
                }
            ])

            results = list(db.orders.aggregate(pipeline))
            output = json.dumps({
                        "results": results,
                        "count": len(results)
                    }, default=str)
            
            print(type(output))
            return output

        # Product ranking
        pipeline.extend([
            {
                "$group": {
                    "_id": "$products.product",
                    "unitsSold": {
                        "$sum": "$products.quantity"
                    },
                    "revenue": {
                        "$sum": {
                            "$multiply": [
                                "$products.quantity",
                                "$products.priceAtPurchase"
                            ]
                        }
                    }
                }
            }
        ])

        if analysis in ["highest_revenue", "product_revenue"]:
            pipeline.append({
                "$sort": {
                    "revenue": -1,"unitsSold": -1,"_id":1
                }
            })
        else:
            pipeline.append({
                "$sort": {
                    "unitsSold": -1,
                    "revenue": -1 ,"_id":1
                }
            })

        pipeline.extend([
            {"$limit": limit},
            {
                "$lookup": {
                    "from": "products",
                    "localField": "_id",
                    "foreignField": "_id",
                    "as": "product"
                }
            },
            {"$unwind": "$product"},
            {
                "$project": {
                    "_id": 0,
                    "productId": "$product._id",
                    "name": "$product.name",
                    "category": "$product.category",
                    "unitsSold": 1,
                    "revenue": 1
                }
            }
        ])

        results = list(db.orders.aggregate(pipeline))

        output = json.dumps({
            "results": results,
            "count": len(results)
        }, default=str)

        print(type(output))
        return output



    return [analyze_products]